apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
 name: wordpress-cert
 namespace: default
spec:
 secretName: wordpress-tls
 issuerRef:
   name: letsencrypt-production
   kind: ClusterIssuer
 commonName: modapeluda.tech
 dnsNames:
 - modapeluda.tech
