apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cGFzc3dvcmQ=      # 'password' en base64
  mysql-user: dXNlcg==                   # 'user' en base64 (puedes cambiarlo si deseas otro nombre de usuario)
  mysql-password: cGFzc3dvcmQ=           # 'password' en base64
  mysql-database: bXlzcWxkYg==           # 'mysqldb' en base64 (puedes cambiarlo si deseas otro nombre de base de datos)
