apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/nfs_share
    server: 50.19.228.205   # IP pública del servidor NFS
  persistentVolumeReclaimPolicy: Retain
